// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.ParkingLot.API.Data;

#nullable disable

namespace Services.ParkingLot.API.Migrations
{
    [DbContext(typeof(ParkingLotDbContext))]
    [Migration("20250906114631_Intial_table_created")]
    partial class Intial_table_created
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Services.ParkingLot.API.Models.Entities.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FloorId"));

                    b.Property<int>("Floor_number")
                        .HasColumnType("int");

                    b.Property<int>("numberOfSlots")
                        .HasColumnType("int");

                    b.HasKey("FloorId");

                    b.HasIndex("Floor_number")
                        .IsUnique();

                    b.ToTable("Floors");
                });
#pragma warning restore 612, 618
        }
    }
}
